package com.d4rk.englishwithlidia.plus.ui.screens.settings.display.theme.style

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

val primaryLight = Color(color = 0xFF904A41)
val onPrimaryLight = Color(color = 0xFFFFFFFF)
val primaryContainerLight = Color(color = 0xFFFFDAD5)
val onPrimaryContainerLight = Color(color = 0xFF3B0906)
val secondaryLight = Color(color = 0xFF775652)
val onSecondaryLight = Color(color = 0xFFFFFFFF)
val secondaryContainerLight = Color(color = 0xFFFFDAD5)
val onSecondaryContainerLight = Color(color = 0xFF2C1512)
val tertiaryLight = Color(color = 0xFF705C2E)
val onTertiaryLight = Color(color = 0xFFFFFFFF)
val tertiaryContainerLight = Color(color = 0xFFFCDFA6)
val onTertiaryContainerLight = Color(color = 0xFF251A00)
val errorLight = Color(color = 0xFFBA1A1A)
val onErrorLight = Color(color = 0xFFFFFFFF)
val errorContainerLight = Color(color = 0xFFFFDAD6)
val onErrorContainerLight = Color(color = 0xFF410002)
val backgroundLight = Color(color = 0xFFFFF8F7)
val onBackgroundLight = Color(color = 0xFF231918)
val surfaceLight = Color(color = 0xFFFFF8F7)
val onSurfaceLight = Color(color = 0xFF231918)
val surfaceVariantLight = Color(color = 0xFFF5DDDA)
val onSurfaceVariantLight = Color(color = 0xFF534341)
val outlineLight = Color(color = 0xFF857370)
val outlineVariantLight = Color(color = 0xFFD8C2BE)
val scrimLight = Color(color = 0xFF000000)
val inverseSurfaceLight = Color(color = 0xFF392E2C)
val inverseOnSurfaceLight = Color(color = 0xFFFFEDEA)
val inversePrimaryLight = Color(color = 0xFFFFB4A9)
val surfaceDimLight = Color(color = 0xFFE8D6D3)
val surfaceBrightLight = Color(color = 0xFFFFF8F7)
val surfaceContainerLowestLight = Color(color = 0xFFFFFFFF)
val surfaceContainerLowLight = Color(color = 0xFFFFF0EE)
val surfaceContainerLight = Color(color = 0xFFFCEAE7)
val surfaceContainerHighLight = Color(color = 0xFFF7E4E1)
val surfaceContainerHighestLight = Color(color = 0xFFF1DEDC)

val primaryDark = Color(color = 0xFFFFB4A9)
val onPrimaryDark = Color(color = 0xFF561E18)
val primaryContainerDark = Color(color = 0xFF73342C)
val onPrimaryContainerDark = Color(color = 0xFFFFDAD5)
val secondaryDark = Color(color = 0xFFE7BDB7)
val onSecondaryDark = Color(color = 0xFF442926)
val secondaryContainerDark = Color(color = 0xFF5D3F3B)
val onSecondaryContainerDark = Color(color = 0xFFFFDAD5)
val tertiaryDark = Color(color = 0xFFDFC38C)
val onTertiaryDark = Color(color = 0xFF3E2E04)
val tertiaryContainerDark = Color(color = 0xFF574419)
val onTertiaryContainerDark = Color(color = 0xFFFCDFA6)
val errorDark = Color(color = 0xFFFFB4AB)
val onErrorDark = Color(color = 0xFF690005)
val errorContainerDark = Color(color = 0xFF93000A)
val onErrorContainerDark = Color(color = 0xFFFFDAD6)
val backgroundDark = Color(color = 0xFF1A1110)
val onBackgroundDark = Color(color = 0xFFF1DEDC)
val surfaceDark = Color(color = 0xFF1A1110)
val onSurfaceDark = Color(color = 0xFFF1DEDC)
val surfaceVariantDark = Color(color = 0xFF534341)
val onSurfaceVariantDark = Color(color = 0xFFD8C2BE)
val outlineDark = Color(color = 0xFFA08C89)
val outlineVariantDark = Color(color = 0xFF534341)
val scrimDark = Color(color = 0xFF000000)
val inverseSurfaceDark = Color(color = 0xFFF1DEDC)
val inverseOnSurfaceDark = Color(color = 0xFF392E2C)
val inversePrimaryDark = Color(color = 0xFF904A41)
val surfaceDimDark = Color(color = 0xFF1A1110)
val surfaceBrightDark = Color(color = 0xFF423735)
val surfaceContainerLowestDark = Color(color = 0xFF140C0B)
val surfaceContainerLowDark = Color(color = 0xFF231918)
val surfaceContainerDark = Color(color = 0xFF271D1C)
val surfaceContainerHighDark = Color(color = 0xFF322826)
val surfaceContainerHighestDark = Color(color = 0xFF3D3231)

object Colors {
    @Composable
    fun primaryText() = MaterialTheme.colorScheme.onBackground

    @Composable
    fun secondaryText() = MaterialTheme.colorScheme.onSurface
}
